- name: Backend Setup
  hosts: all
  become: true
  tasks:
    - name: Disable node
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJS module for V20
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install Node js
      ansible.builtin.dnf:
        name: nodejs
        state: latest

    - name: Adding user
      ansible.builtin.user:
        name: expense

    - name: Copy backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: delete content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Creating directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading and unzip app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Npm Install
      community.general.npm:
        path: /app
        state: latest

#    - name: Install MySql
#      ansible.builtin.dnf:
#        name: mysql
#        state: latest

    - name: Install Python MySql Client
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.9

    - name: Add Schema
      community.mysql.mysql_db:
        name: all
        state: import
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.prakhardevopslearning.online

    - name: Enable & Start backend Service
      ansible.builtin.systemd_service:
        state: restarted
        name: backend
        enabled: yes
        daemon_reload: yes
