- name: Front end Setup
  hosts: all
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Copy conf file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: delete content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Creating directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: downloading and unzip app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: start nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
        enabled: yes

