- name: MySql Setup
  hosts: all
  become: true
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: enable & start mysqlId
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes

    - name: Set MySql Pwd
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
