- name: MySql Setup
  hosts: all
  become: true
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: enable & start mysqlId
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes

    - name: Set MySql Pwd
      community.mysql.mysql_db:
        login_user: root
        login_password: ExpenseApp@1
