- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import application prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: start nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: yes