component: backend
app_loc: /app
app_user: expense   #added when we need to make "expense" as Owner for the access of directory app to get the new relic agent log
rsyslog_config_needed: true
log_file: /var/log/backend.log

