- name: delete content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Creating directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

- name: downloading and unzip app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_loc }}"
    remote_src: yes