- name: Set Prompt with component
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus_node_exporter
    tasks_from: node_exporter

- name: Install Logstash
  ansible.builtin.import_role:
    name: logstash
    tasks_from: logstash.yml